# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Create a bug report regarding GeoAlchemy 2 runtime behavior
description: Errors and regression reports with complete reproducing test cases and/or stack traces.
labels: [bug]
title: "[Bug report] "
body:
  - type: markdown
    attributes:
      value: "
Thanks for taking the time to fill out this bug report!


Before submitting, make sure you search in the [issue list](https://github.com/geoalchemy/geoalchemy2/issues) that a similar issue was not already reported.
If it is not the case, please read the following guidelines.

### GUIDELINES FOR REPORTING BUGS

Bug reports that are not properly formulated and formatted or without enough details can be very hard for us to understand and fix.
In order to ensure we can help you fixing your bug, please follow these guidelines.


Your reports must include the following features:

1. **succinct description** of the problem - typically a line or two at most.

2. **succinct, dependency-free code** which reproduces the problem, otherwise known as a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example.
  **Please note that if you do not have a complete and runnable test case written directly in the textarea below, then your issue will be very hard for us to process and may be closed.**

3. **complete stack traces for all errors** - please avoid screenshots, use formatted text inside issues.

4. other relevant things as applicable: **dependencies**, **comparative performance timings** for performance issues, etc.
"

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    id: relevant_documentation
    attributes:
      label: Optional link from https://geoalchemy-2.readthedocs.io which documents the behavior that is expected
      description: "
Please make sure the behavior you are seeing is definitely in contradiction to what's documented as the correct behavior.
"
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      description: "
Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example here."
      placeholder: "# Insert code here (text area already python formatted)"
      render: Python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: "
Provide the complete text of any errors received **including the complete stack trace**.
If the message is a warning, run your program with the ``-Werror`` flag: ``python -Werror myprogram.py``
"
      placeholder: "# Copy the complete stack trace and error message here (text area already formatted for Python backtrace)"
      render: Python traceback
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: input
    id: package_version
    attributes:
      label: GeoAlchemy 2 Version in Use
      description: e.g. 1.4.42, 2.0.2, etc or commit hash
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Assumes cpython unless otherwise stated, e.g. 3.10, 3.11, pypy
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Check all that apply
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Thanks! Have a nice day!"
