# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Ask for help about GeoAlchemy 2
description: Questions about GeoAlchemy 2 features.
labels: [how to use]
title: "[How to use] "
body:
  - type: markdown
    attributes:
      value: "
Thanks for using this package and taking the time to fill out this help request!


Before submitting, make sure you read the [documentation](https://geoalchemy-2.readthedocs.io) carefully.
If you still have a question, you should search in the [issue list](https://github.com/geoalchemy/geoalchemy2/issues) that a similar issue has not already been reported, you might find your answer there.
If it is not the case, please read the following guidelines.

### GUIDELINES FOR REQUESTING HELP

Questions that are not properly formulated and formatted or without enough details can be very hard for us to understand.
In order to ensure we can help you, please follow these guidelines.


Your requests must include the following features:

1. **succinct description** of the problem - typically a line or two at most to describe what you want to achieve.

2. **succinct, dependency-free code** which shows what you tried to do, otherwise known as a [Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/mcve).

3. **expected results**

4. **complete stack traces for all errors** if you have any - please avoid screenshots, use formatted text inside issues.

5. other relevant things: **dependencies**, **operating system**, **comparative performance timings** for performance issues.
"

  - type: textarea
    attributes:
      label: Describe the problem
      description: A clear and concise description of what you want to achieve.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Show what you tried to do.
      description: "
Provide your [Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/mcve) here."
      placeholder: "# Insert code here (text area already python formatted)"
      render: Python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe what you expected.
      description: A clear and concise description of what you which result you expected by doing this.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: "
If you are facing an arror, provide the complete text of any errors received **including the complete stack trace**.
If the message is a warning, run your program with the ``-Werror`` flag: ``python -Werror myprogram.py``
"
      placeholder: "# Copy the complete stack trace and error message here (text area already formatted for Python backtrace)"
      render: Python traceback
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: input
    id: package_version
    attributes:
      label: GeoAlchemy 2 Version in Use
      description: e.g. 1.4.42, 2.0.2, etc or commit hash
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Thanks! Have a nice day!"
